### Get all user data
GET {{host}}/users
### Find user by id
GET {{host}}/users/find/5
### Get user product
# relation/('product', 'cart')
GET {{host}}/users/relation/product
### Logout
GET {{host}}/users/logout
### Delete user by id
DELETE {{host}}/users/1

### Register
POST {{host}}/users/register
Content-Type: application/json

{
  "name": "wahyu triono",
  "email": "ssa@dmail.com",
  "password": "qweasdzxc",
  "confirmPassword": "qweasdzxc"
}

### Login
POST {{host}}/users/login
Content-Type: application/json

{
  "email": "ssa@dmail.com",
  "password": "qweasdzxc"
}

### Update user by id
PUT {{host}}/users/1
Content-Type: application/json

{
  "name": "wahyu triono",
  "email": "sa@dmail.com",
  "password": "qweasdzxc",
  "confirmPassword": "qweasdzxc"
}